### ISSUE TITLE
ssl_exporter dont export timestamp to prometheus

### ISSUE THREAD

**Issue by petersg** [ribbybibby/ssl_exporter#115]
Hello all,

I have configured ssl_exporter to check some certs and display it into prometheus -> grafana.

My job config:
`- job_name: "ssl"
      metrics_path: /probe
      params:
        module: ["https"]
      static_configs:
        - targets:
          - "helloworld.letsencrypt.org:443"
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 10.10.20.14:9219
`
If i check the route with(http://127.0.0.1:9219/probe?module=https&target=helloworld.letsencrypt.org:443) i can see that is correctly scraping it with the timestamp:
![image](https://user-images.githubusercontent.com/22115303/196686522-a1b33094-9178-4b2d-8034-3c9fa0ab2f40.png)
But when i go to prometheus and see the output:
![image](https://user-images.githubusercontent.com/22115303/196686671-3e87892d-5e1a-4c04-b6be-96ee289f6372.png)
Is missing the timestamp so i can not visualize the remain time to expire and others. It can be because it is out of the {}?

Kind Regards,
Petar

**Comment by britcey** [comment]
The timestamp is the _value_ of the metric - it's not one of the labels.  It's a Unix timestamp (seconds since midnight Jan 1, 1970).

ssl_cert_not_after - time() 

will give you seconds until expiration

(ssl_cert_not_after - time()) / 86400

will give you days until expiration, etc.

You can use 'humanizeTimestamp' in your alerts to show the actual date of expiration.  I include an annotation like:

    expiration_time: |
            {{ with printf "ssl_cert_not_after{serial_no='%s'}" .Labels.serial_no |query }}{{ . | first | value | humanizeTimestamp }}{{ end }}

**Comment by petersg** [comment]
Ok solved, it seems that grafana cant read correctly the $instance and $job but removing this or hardcoded it fix the issue.
