### ISSUE TITLE
How can I custom the resolve IP for tls certificate check ?

### ISSUE THREAD

**Issue by leo69github** [ribbybibby/ssl_exporter#120]
How can I custom the resolve IP or domain for tls certificate check ?

I used to monitor the Certificate by Blackbox Exporter as below, I can manul setting the IP address and domain.
http://10.0.8.77:9115/probe?module=http_2xx&target=https://172.217.163.36&hostname=www.google.com&debug=true

Recently Athough I successed via specify "server_name" in Module, but It looks like I need create a lot of modules to monitor a mount of domain and IP address.

Is there any advice to do this perpose?

**Comment by ribbybibby** [comment]
Currently the only option is to set `server_name` in the module configuration. This has been requested before but I erred on the side of following the blackbox_exporter, which previously didn't support the hostname parameter.

Now that the blackbox_exporter does support hostname, perhaps the ssl_exporter should follow suit.

**Comment by leo69github** [comment]
I found answer with below 
https://github.com/ribbybibby/ssl_exporter/pull/80/commits/978a8a83f019ad369e18c063685001709dbde601

Thanks
