### ISSUE TITLE
What format is the serial number in?

### ISSUE THREAD

**Issue by alvnov** [ribbybibby/ssl_exporter#123]
Hi all
What is the format of serial_no="nnn.." key serial number?
I see 39 digits in decimal, but I need hexadecimal. But the conversion from decimal to hexadecimal does not give me anything. I do not have with the correct serial number (

**Comment by ribbybibby** [comment]
The serial number comes from the `SerialNumber` field of the [`x509.Certificate`](https://pkg.go.dev/crypto/x509#Certificate) type. This is a [`big.Int`](https://pkg.go.dev/math/big#Int), which we call [`String()`](https://pkg.go.dev/math/big#Int.String) on.

According to the description for `String`:
> String returns the decimal representation of x as generated by x.Text(10).

And then for `Text`:
> Text returns the string representation of x in the given base. Base must be between 2 and 62, inclusive. The result uses the lower-case letters 'a' to 'z' for digit values 10 to 35, and the upper-case letters 'A' to 'Z' for digit values 36 to 61. No prefix (such as "0x") is added to the string. If x is a nil pointer it returns "<nil>".
