### ISSUE TITLE
Allow to use remote http\https resources in PEM file module

### ISSUE THREAD

**Issue by dragoangel** [ribbybibby/ssl_exporter#147]
With BIMI (and some other usecases) it's common to have PEM file stored on some public storage, it could be verified with file module potentially, or we can create dedicated module for http_file with additional settings to trust invalid cert of https server or not, etc

**Comment by ribbybibby** [comment]
https://github.com/ribbybibby/ssl_exporter/pull/144 - related PR

**Comment by dragoangel** [comment]
Nice! @ribbybibby can this be merged?

**Comment by ribbybibby** [comment]
Added in #144.
