### ISSUE TITLE
FR: Add support for StartTLS

### ISSUE THREAD

**Issue by dragoangel** [ribbybibby/ssl_exporter#29]
To check SSL on some services StartTLS must be supported, it would be cool if you add such support. Thank you in advance.
There is already pull request #21 for SMTP, but it doesn't merged.
Additionally to SMTP - IMAP, POP3, LDAP, XMPP and FTP are rely on StartTLS https://en.wikipedia.org/wiki/Opportunistic_TLS

**Comment by dragoangel** [comment]
Oh there already pull request but it doesn't merged. #21

**Comment by ribbybibby** [comment]
See: #36

**Comment by ribbybibby** [comment]
Support was added for SMTP, IMAP and FTP in v2.0.0.

I'm going to look at adding more protocols soon.

**Comment by dragoangel** [comment]
Hi @ribbybibby Big thank you! Also do you think about DANE validation support inside your plugin? Is that thermostatically possible?
