### ISSUE TITLE
date expire from pem or crt files

### ISSUE THREAD

**Issue by Nurlan199206** [ribbybibby/ssl_exporter#40]
It's possible to checks date expire from pem or crt files?

**Comment by ribbybibby** [comment]
Hi @Nurlan199206. This exporter doesn't directly support scraping certificate metrics from files but what you could do is serve the files and then scrape them that way.

For instance:
```
$ openssl s_server -cert tls.crt -key tls.key -accept 8443
Using auto DH parameters
Using default temp ECDH parameters
ACCEPT
``` 

This will serve tls.crt on port 8443, which will allow you to probe it on `<server IP>:8443`.
