### ISSUE TITLE
Metric name ssl_verfied_cert_not_after typo, should be ssl_verified_cert_not_after

### ISSUE THREAD

**Issue by nia1048596** [ribbybibby/ssl_exporter#51]
Hi,

There is a typo in the metric name `ssl_verfied_cert_not_after`, missing an `i` in `verified`.

**Comment by ribbybibby** [comment]
Hi @nia1048596, thanks for pointing this out!

Not only was the name wrong, the test that should have caught this was wrong as well. I've sorted both and this should be resolved in 2.1.1.
