### ISSUE TITLE
Exporting OCSP stapling information

### ISSUE THREAD

**Issue by tykling** [ribbybibby/ssl_exporter#52]
Hello,
I am in need of an exporter to give information about OCSP stapling for TLS handshakes. Would you be interested in adding such a feature in ssl_exporter? I need the this_update/produced_at/next_update times/ages to monitor the freshness of OCSP stapling in my TLS servers.

**Comment by ribbybibby** [comment]
I'm always interested in expanding the usefulness of this exporter 😄 . It seems like the OCSPResponse is available in the connection state (https://golang.org/src/crypto/tls/common.go?#L269) so it should be possible to parse that into metrics.

I don't have any prior knowledge of OCSP so I'll need to play around with it a bit.

**Comment by tykling** [comment]
Fantastic. I've dipped my toes a few times (and I recently implemented an OCSP client in my ACME/LetsEncrypt thing Certgrinder), so let me know if there is anything I can do :+1:

**Comment by ribbybibby** [comment]
https://github.com/ribbybibby/ssl_exporter/pull/54

**Comment by ribbybibby** [comment]
Released in v2.2.0.
