### ISSUE TITLE
Output of ssl_exporter shown in scientifc format

### ISSUE THREAD

**Issue by ScrumpyJack** [ribbybibby/ssl_exporter#6]
Do you know why I would be getting epoch time converted into scientific notation?

```
ssl_cert_not_after{issuer_cn="DigiCert Global Root CA",serial_no="xxx"} 1.6782768e+09
ssl_cert_not_after{issuer_cn="DigiCert SHA2 Secure Server CA",serial_no="xxx"} 1.598616e+09
```

**Comment by ribbybibby** [comment]
I don't know why exactly but the representation of the value comes from the client library and is understood correctly by Prometheus, so it shouldn't be an issue.

I've always assumed that it happens when a number exceeds a certain size.

**Comment by ScrumpyJack** [comment]
I'll try scraping and see what I get in Prometheus

**Comment by ribbybibby** [comment]
@ScrumpyJack how did you get on?
