### ISSUE TITLE
blackbox?

### ISSUE THREAD

**Issue by le-shi** [ribbybibby/ssl_exporter#64]
A revamped Blockbox?

**Comment by ribbybibby** [comment]
The `tcp` and `https` probers are adapted from the blackbox_exporter but they export richer metrics about TLS certificates. This exporter could replace the blackbox_exporter as a TLS monitor, if you could benefit from the extra information it provides. I will always try to ensure that, as it relates to TLS, this exporter matches and exceeds the capabilities of the blackbox_exporter.

**Comment by le-shi** [comment]
Come on, look good on you :+1:

**Comment by debuglevel** [comment]
It just took me quite some time to figure out what the benefits over blackbox are :-). Maybe you could outline the advantages in the README? :)
