### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by Scrin** [ribbybibby/ssl_exporter#86]
With an increasing number of available arm64 servers (and usually cheaper than amd64) these days, it would be nice to have arm64 versions of the releases and docker images to avoid needing to build my own for my arm64 based servers

**Comment by ribbybibby** [comment]
Thanks for the suggestion! I've added additional arch targets and multi-platform docker images [here](https://github.com/ribbybibby/ssl_exporter/commit/8e318931c52ec77cc2587c6e1f16dbc7e9499d68) and [here](https://github.com/ribbybibby/ssl_exporter/commit/d38244bc39105f83c22305f23f0448a590a1ef6b).

They'll be available in the next release.
