### ISSUE TITLE
Monitor certs on tcp endpoints with SAN given?

### ISSUE THREAD

**Issue by KlavsKlavsen** [ribbybibby/ssl_exporter#87]
Can this monitor certs on none-active loadbalancer?
I have 2 loadbalancers - both have copy of certs - but sometimes the copy to secondary fails and I'd like to monitor this.
What I do now (old icinga setup) is to simply tell my https checker to use ip of 'localhost' - and set Host: header to the domain I want to check cert for (its a standard https checker) and it then instructs SSL layer that SNI name is the hostname set in Host header and this works great for overriding what IP it goes to - for checking if the domain cert.

**Comment by ribbybibby** [comment]
You can set the `tls_config.server_name` parameter in a custom module configuration. See an example of that [here](https://github.com/ribbybibby/ssl_exporter/blob/master/examples/ssl_exporter.yaml#L22-L25).
