### ISSUE TITLE
Is the go.mod file broken?

### ISSUE THREAD

**Issue by jamesalbert** [ribbybibby/ssl_exporter#91]
Noticed:
```
$ go list -m -versions github.com/ribbybibby/ssl_exporter
github.com/ribbybibby/ssl_exporter v0.1.0 v0.2.0 v0.3.0 v0.4.0 v0.5.0 v0.6.0 v1.0.0-rc.0 v1.0.0-test-tag v1.0.0-test-tag2 v1.0.0 v1.0.1
```

which is a bit behind recent releases. Without knowing too much about why this would happen, [this SO answer](https://stackoverflow.com/questions/63013135/what-to-do-when-go-list-doesnt-show-the-newest-version-of-a-package) suggests the go.mod file might be invalid, but I'm not sure. Is there any more info on this?

**Comment by jamesalbert** [comment]
also, when trying to get the latest version directly, I get:

```
$ go get github.com/ribbybibby/ssl_exporter@master
github.com/ribbybibby/ssl_exporter imports
        github.com/ribbybibby/ssl_exporter/prober imports
        k8s.io/client-go/kubernetes: cannot find module providing package k8s.io/client-go/kubernetes
github.com/ribbybibby/ssl_exporter imports
        github.com/ribbybibby/ssl_exporter/prober imports
        k8s.io/client-go/plugin/pkg/client/auth/oidc: cannot find module providing package k8s.io/client-go/plugin/pkg/client/auth/oidc
github.com/ribbybibby/ssl_exporter imports
        github.com/ribbybibby/ssl_exporter/prober imports
        k8s.io/client-go/tools/clientcmd: cannot find module providing package k8s.io/client-go/tools/clientcmd
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.
```

**Comment by jamesalbert** [comment]
for additional context, I was able to import this package by [forking this repo](https://github.com/jamesalbert/ssl_exporter) and regenerating the go.mod file. Granted, I'm a go noob these days, so take what I did with a grain of salt. It looks like it added packages that weren't there originally

**Comment by jamesalbert** [comment]
Nice @ribbybibby glad to here that's the case. I was scratching my head at that for a bit :smile:

I actually have an open pull request to include this project into grafana/agent: https://github.com/grafana/agent/pull/1692

That PR is currently pointed to my fork and I was really hoping to point it back to yours once this was resolved. Would really like to use this exporter in our grafana stack.

**Comment by jamesalbert** [comment]
@ribbybibby when I regenerated go.mod, I didn't notice any module path change, but whatever it did, it allowed me to pull the most recent version. If I rename all those references back to their original, would you mind taking this as a pr: https://github.com/ribbybibby/ssl_exporter/compare/master...jamesalbert:master

or maybe there's other stuff you wanted to add? I'm not sure

**Comment by ribbybibby** [comment]
I've made the module path change and cut a new version. Can you try importing with:
```
require github.com/ribbybibby/ssl_exporter/v2 v2.4.1
```

This seems to work for me.

**Comment by jamesalbert** [comment]
Thanks for updating that! There seems to be one more point of contention (at least integrating it into that project). I think it's here: https://github.com/ribbybibby/ssl_exporter/blob/master/go.mod#L14

k8s.io/client-go@1.5.2 (different from the rest of the k8s.io dependencies at 0.24.0) seems to break version requirements. I'm getting a lot of

```
 k8s.io/client-go/metadata: package k8s.io/client-go/metadata provided by k8s.io/client-go at latest version v0.24.0 but not at required version v1.5.2
```

I noticed my fork brought it back down to 0.24.0. Is there any way we can pin it back down?
